### ISSUE TITLE
add  joi validation to the schemas

### ISSUE THREAD

**Issue by Sukriti-m** [aditya-singh9/url-shotener-backend-ts#6]
I will add the joi validation to the schemas present

Please assign this issue to me and add the 'hacktoberfest' label to it. @aditya-singh9

**Comment by aditya-singh9** [comment]
Please explain, what is joi validation and its benefit in this application.

**Comment by Sukriti-m** [comment]
> Please explain, what is joi validation and its benefit in this application.

Joi module is a popular module for data validation. This module validates the data based on schemas. There are various functions like optional(), required(), min(), max(), etc which make it easy to use and a user-friendly module for validating the data.
Also, it is much secure than the traditional mongoDB validations.
